openapi: 3.0.0
info:
  title: RAG Chatbot API
  version: 1.0.0
  description: API for interacting with the RAG (Retrieval-Augmented Generation) chatbot for the Physical AI & Humanoid Robotics textbook.
servers:
  - url: /
    description: Local development server
paths:
  /chat:
    post:
      summary: Submit a user query to the RAG chatbot
      operationId: submitQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserQuery'
      responses:
        '200':
          description: Successful RAG response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RAGResponse'
        '400':
          description: Invalid query or missing parameters
        '500':
          description: Internal server error or RAG backend issue
  /contextual-chat:
    post:
      summary: Submit a contextual user query based on selected text
      operationId: submitContextualQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
                - context_text
              properties:
                query:
                  type: string
                  description: The user's question.
                context_text:
                  type: string
                  description: The text selected by the user from the textbook to provide context.
      responses:
        '200':
          description: Successful RAG response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RAGResponse'
        '400':
          description: Invalid query or missing parameters
        '500':
          description: Internal server error or RAG backend issue

components:
  schemas:
    UserQuery:
      type: object
      required:
        - text
      properties:
        text:
          type: string
          description: The user's question.
        timestamp:
          type: string
          format: date-time
          description: Timestamp when the query was made.

    RAGResponse:
      type: object
      required:
        - response_text
        - source_chapters
      properties:
        response_text:
          type: string
          description: The synthesized answer provided by the chatbot.
        source_chapters:
          type: array
          items:
            type: string
          description: A list of chapter IDs or references from which the answer was derived.
        timestamp:
          type: string
          format: date-time
          description: Timestamp when the response was generated.
